services:
  mysql:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: SithijaSQL
      MYSQL_DATABASE: travel
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./local_db_dump.sql:/docker-entrypoint-initdb.d/local_db_dump.sql
    networks:
      - app-network

  consul:
    image: consul:1.14.3
    container_name: consul
    command: agent -dev -client=0.0.0.0
    ports:
      - "8500:8500"
      - "8300-8302:8300-8302"
      - "8301-8302:8301-8302/udp"
      - "8600:8600"
      - "8600:8600/udp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8500/v1/status/leader" ]
      interval: 20s
      timeout: 5s
      retries: 10
    volumes:
      - consul-data:/consul/data
    networks:
      - app-network

  comment-service:
    image: comment-service-image
    container_name: comment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/travel
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SithijaSQL
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    depends_on:
      consul:
        condition: service_healthy
#      consul:
#        condition: service_started
      mysql:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - app-network

  user-service:
    image: user-service-image
    container_name: user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/travel
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SithijaSQL
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
    depends_on:
      consul:
        condition: service_healthy
      mysql:
        condition: service_started
    ports:
      - "8082:8082"
    networks:
      - app-network

  post-service:
    image: post-service-image
    container_name: post-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/travel
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: SithijaSQL
      SPRING_CLOUD_CONSUL_HOST: consul
      SPRING_CLOUD_CONSUL_PORT: 8500
      SPRING_CACHE_TYPE: redis
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_CACHE_REDIS_CACHE_NULL_VALUES: true
      SPRING_CACHE_REDIS_TIME_TO_LIVE: 3600000
    depends_on:
      consul:
        condition: service_healthy
      mysql:
        condition: service_started
    ports:
      - "8081:8081"
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    name: app-network

volumes:
  mysql-data:
  consul-data: