apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-set
spec:
  selector:
    matchLabels:
      app: mysql-set
  serviceName: mysql-set
  replicas: 2
  template:
    metadata:
      labels:
        app: mysql-set
    spec:
      containers:
        - name: mysql
          image: mysql:latest
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-store
              mountPath: /var/lib/mysql
          env:
#            - name: SPRING_DATASOURCE_PASSWORD
#              valueFrom:
#                secretKeyRef:
#                  name: app-secrets
#                  key: SPRING_DATASOURCE_PASSWORD
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: MYSQL_ROOT_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: mysql-store
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-set
  labels:
    app: mysql-set
spec:
  type: ClusterIP
  selector:
    app: mysql-set
  ports:
    - port: 3306
      protocol: TCP
  clusterIP: "None"

---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard
provisioner: k8s.io/minikube-hostpath
volumeBindingMode: Immediate
